//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRole
    {
        public AspNetRole()
        {
            this.subjects = new HashSet<subject>();
            this.galleries = new HashSet<gallery>();
            this.images = new HashSet<image>();
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<subject> subjects { get; set; }
        public virtual ICollection<gallery> galleries { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}
