//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.comments = new HashSet<comment>();
            this.naming_corrections = new HashSet<naming_corrections>();
            this.galleries = new HashSet<gallery>();
            this.gallery_images = new HashSet<gallery_images>();
            this.gallery_reports = new HashSet<gallery_reports>();
            this.image_tags = new HashSet<image_tags>();
            this.images = new HashSet<image>();
            this.image_reports = new HashSet<image_reports>();
            this.subject_reports = new HashSet<subject_reports>();
            this.subjects = new HashSet<subject>();
            this.AspNetRoles = new HashSet<AspNetRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<naming_corrections> naming_corrections { get; set; }
        public virtual ICollection<gallery> galleries { get; set; }
        public virtual ICollection<gallery_images> gallery_images { get; set; }
        public virtual ICollection<gallery_reports> gallery_reports { get; set; }
        public virtual ICollection<image_tags> image_tags { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<image_reports> image_reports { get; set; }
        public virtual ICollection<subject_reports> subject_reports { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
        public virtual ICollection<AspNetRole> AspNetRoles { get; set; }
    }
}
