//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.galleries = new HashSet<gallery>();
            this.images = new HashSet<image>();
            this.subjects = new HashSet<subject>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public short AgeRestricted { get; set; }
    
        public virtual ICollection<gallery> galleries { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
    }
}
