//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.comments1 = new HashSet<comment>();
            this.comments = new HashSet<comment>();
            this.galleries = new HashSet<gallery>();
            this.images = new HashSet<image>();
            this.subjects = new HashSet<subject>();
        }
    
        public int CommentID { get; set; }
        public string UserID { get; set; }
        public System.DateTime Date { get; set; }
        public short IsReported { get; set; }
        public string Comment1 { get; set; }
        public short IsHidden { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<comment> comments1 { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<gallery> galleries { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
    }
}
