//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class gallery
    {
        public gallery()
        {
            this.gallery_images = new HashSet<gallery_images>();
            this.gallery_ratings = new HashSet<gallery_ratings>();
            this.gallery_reports = new HashSet<gallery_reports>();
            this.gallery_votes = new HashSet<gallery_votes>();
            this.naming_corrections = new HashSet<naming_corrections>();
            this.categories = new HashSet<category>();
            this.comments = new HashSet<comment>();
            this.subjects = new HashSet<subject>();
        }
    
        public int GalleryID { get; set; }
        public string GalleryName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string CreatedBy { get; set; }
        public long TimesViewed { get; set; }
        public short Reported { get; set; }
        public string PermissionLevel { get; set; }
        public short AgeRestricted { get; set; }
        public short IsHidden { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<gallery_images> gallery_images { get; set; }
        public virtual ICollection<gallery_ratings> gallery_ratings { get; set; }
        public virtual ICollection<gallery_reports> gallery_reports { get; set; }
        public virtual ICollection<gallery_votes> gallery_votes { get; set; }
        public virtual ICollection<naming_corrections> naming_corrections { get; set; }
        public virtual ICollection<category> categories { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
    }
}
