//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public image()
        {
            this.gallery_images = new HashSet<gallery_images>();
            this.image_tags = new HashSet<image_tags>();
            this.image_ratings = new HashSet<image_ratings>();
            this.image_reports = new HashSet<image_reports>();
            this.image_votes = new HashSet<image_votes>();
            this.naming_corrections = new HashSet<naming_corrections>();
            this.subjects = new HashSet<subject>();
            this.thumbnails = new HashSet<thumbnail>();
            this.categories = new HashSet<category>();
            this.comments = new HashSet<comment>();
            this.subjects1 = new HashSet<subject>();
        }
    
        public int ImageID { get; set; }
        public int LocationID { get; set; }
        public string Filename { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
        public short Reported { get; set; }
        public string PermissionLevel { get; set; }
        public short AgeRestricted { get; set; }
        public string FileType { get; set; }
        public short IsHidden { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public string Orientation { get; set; }
        public string Description { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<gallery_images> gallery_images { get; set; }
        public virtual ICollection<image_tags> image_tags { get; set; }
        public virtual site_locations site_locations { get; set; }
        public virtual ICollection<image_ratings> image_ratings { get; set; }
        public virtual ICollection<image_reports> image_reports { get; set; }
        public virtual ICollection<image_votes> image_votes { get; set; }
        public virtual ICollection<naming_corrections> naming_corrections { get; set; }
        public virtual ICollection<subject> subjects { get; set; }
        public virtual ICollection<thumbnail> thumbnails { get; set; }
        public virtual ICollection<category> categories { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<subject> subjects1 { get; set; }
    }
}
