//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class naming_corrections
    {
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> GalleryID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string CorrectedBy { get; set; }
        public string CorrectedEntry { get; set; }
        public System.DateTime DateOfCorrection { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual gallery gallery { get; set; }
        public virtual image image { get; set; }
        public virtual subject subject { get; set; }
    }
}
