//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_types
    {
        public report_types()
        {
            this.gallery_reports = new HashSet<gallery_reports>();
            this.image_reports = new HashSet<image_reports>();
            this.subject_reports = new HashSet<subject_reports>();
        }
    
        public int ReportTypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<gallery_reports> gallery_reports { get; set; }
        public virtual ICollection<image_reports> image_reports { get; set; }
        public virtual ICollection<subject_reports> subject_reports { get; set; }
    }
}
