//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class site_locations
    {
        public site_locations()
        {
            this.images = new HashSet<image>();
            this.thumbnails = new HashSet<thumbnail>();
        }
    
        public int LocationID { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<image> images { get; set; }
        public virtual ICollection<thumbnail> thumbnails { get; set; }
    }
}
