//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_external_links
    {
        public int LinkID { get; set; }
        public int SubjectID { get; set; }
        public string URL { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
    
        public virtual subject subject { get; set; }
        public virtual subject_external_links_type subject_external_links_type { get; set; }
    }
}
