//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_external_links_type
    {
        public subject_external_links_type()
        {
            this.subject_external_links = new HashSet<subject_external_links>();
        }
    
        public int LinkTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<subject_external_links> subject_external_links { get; set; }
    }
}
