//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        public subject()
        {
            this.naming_corrections = new HashSet<naming_corrections>();
            this.subject_alias = new HashSet<subject_alias>();
            this.subject_external_links = new HashSet<subject_external_links>();
            this.subject_rating = new HashSet<subject_rating>();
            this.subject_reports = new HashSet<subject_reports>();
            this.subject_votes = new HashSet<subject_votes>();
            this.galleries = new HashSet<gallery>();
            this.categories = new HashSet<category>();
            this.comments = new HashSet<comment>();
            this.images = new HashSet<image>();
        }
    
        public int SubjectID { get; set; }
        public string Name { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Nationality { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string AddedBy { get; set; }
        public short Reported { get; set; }
        public Nullable<int> ProfilePicId { get; set; }
        public string PermissionLevel { get; set; }
        public short AgeRestricted { get; set; }
        public short IsHidden { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual image image { get; set; }
        public virtual ICollection<naming_corrections> naming_corrections { get; set; }
        public virtual ICollection<subject_alias> subject_alias { get; set; }
        public virtual ICollection<subject_external_links> subject_external_links { get; set; }
        public virtual ICollection<subject_rating> subject_rating { get; set; }
        public virtual ICollection<subject_reports> subject_reports { get; set; }
        public virtual ICollection<subject_votes> subject_votes { get; set; }
        public virtual ICollection<gallery> galleries { get; set; }
        public virtual ICollection<category> categories { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<image> images { get; set; }
    }
}
