//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class thumbnail
    {
        public int ThumbnailID { get; set; }
        public int LocationID { get; set; }
        public string Filename { get; set; }
        public int MainImageID { get; set; }
        public string FileType { get; set; }
        public short IsHidden { get; set; }
    
        public virtual image image { get; set; }
        public virtual site_locations site_locations { get; set; }
    }
}
