//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGalleryImage
    {
        public int GalleryID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Filename { get; set; }
        public string ImageDescription { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string AddedBy { get; set; }
        public long TimesViewed { get; set; }
        public string GalleryName { get; set; }
        public long ImageTimesViewed { get; set; }
        public string PermissionLevel { get; set; }
        public short AgeRestricted { get; set; }
        public string GalleryDescription { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public int SubjectID { get; set; }
        public short IsHidden { get; set; }
        public int ImageID { get; set; }
    }
}
