//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllGallery
    {
        public string CategoryName { get; set; }
        public string GalleryName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public string SubjectName { get; set; }
        public short IsHidden { get; set; }
        public string CreatedBy { get; set; }
        public short AgeRestricted { get; set; }
        public string PermissionLevel { get; set; }
        public short Reported { get; set; }
        public long TimesViewed { get; set; }
        public string Description { get; set; }
        public short CategoryRestricted { get; set; }
        public int GalleryID { get; set; }
    }
}
