//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSubjectImage
    {
        public int ImageID { get; set; }
        public int LocationID { get; set; }
        public string Filename { get; set; }
        public string Name { get; set; }
        public int SubjectID { get; set; }
        public string Location { get; set; }
    }
}
