//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGalleryVote
    {
        public int GalleryID { get; set; }
        public string VoteType { get; set; }
        public Nullable<int> TotalVotes { get; set; }
    }
}
