//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAllImage
    {
        public int ImageID { get; set; }
        public string Filename { get; set; }
        public System.DateTime DateAdded { get; set; }
        public short Reported { get; set; }
        public string PermissionLevel { get; set; }
        public short AgeRestricted { get; set; }
        public short IsHidden { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
    }
}
