//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class vote_type
    {
        public vote_type()
        {
            this.gallery_votes = new HashSet<gallery_votes>();
            this.image_votes = new HashSet<image_votes>();
            this.subject_votes = new HashSet<subject_votes>();
        }
    
        public int VoteTypeId { get; set; }
        public string VoteType { get; set; }
    
        public virtual ICollection<gallery_votes> gallery_votes { get; set; }
        public virtual ICollection<image_votes> image_votes { get; set; }
        public virtual ICollection<subject_votes> subject_votes { get; set; }
    }
}
